.github/workflows/ci.yml#     - name: Run the tests and generate coverage report
#       run: npm test -- --coverage
      
#     - name: Upload coverage to Codecov
#       uses: codecov/codecov-action@v1   
#       with:
#         token: ${{ secrets.CODECOV_TOKEN }}
name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.noede-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Check out your repository
    - name: Install dependencies
      run: npm install
    
    - name: Install truffle
      run: npm install --save-dev truffle
    - run: yarn # Install dependencies
    - run: yarn test --coverage # Run test
    - run: bash <(curl -s https://codecov.io/bash) # Upload to Codecov
    - name: Run the tests and generate coverage report
      run: npx truffle test 
